### ISSUE TITLE
Error: web3 RPC failed: {"code":-32000,"message":"execution reverted"} when deploying Foreign Bridge

### ISSUE THREAD

**Issue by schobo** [poanetwork/tokenbridge-contracts#655]
Hi 
I am deploying Tokenbridge contracts with ERC_TO_NATIVE mode from ropsten (Foreign) to my private blockchain (Home) but got this error. Deploying HomeBridge is successful but ForeignBridge always got this error.

Error: web3 RPC failed: {"code":-32000,"message":"execution reverted"}
    at sendNodeRequest (/opt/tokenbridge/contracts/deploy/src/deploymentUtils.js:161:9)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async sendRawTx (/opt/tokenbridge/contracts/deploy/src/deploymentUtils.js:102:36)
    at async initializeBridge (/opt/tokenbridge/contracts/deploy/src/erc_to_native/foreign.js:72:30)
    at async deployForeign (/opt/tokenbridge/contracts/deploy/src/erc_to_native/foreign.js:176:3)
    at async deployErcToNative (/opt/tokenbridge/contracts/deploy/deploy.js:20:29)
    at async main (/opt/tokenbridge/contracts/deploy/deploy.js:87:7)
Error: TypeError: Cannot read property 'status' of undefined
    at initializeBridge (/opt/tokenbridge/contracts/deploy/src/erc_to_native/foreign.js:79:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async deployForeign (/opt/tokenbridge/contracts/deploy/src/erc_to_native/foreign.js:176:3)
    at async deployErcToNative (/opt/tokenbridge/contracts/deploy/deploy.js:20:29)
    at async main (/opt/tokenbridge/contracts/deploy/deploy.js:87:7)
I searched on google but I can't find anything relate to this error. Could you please help? If you need any other information please let me know. 

Thank you.

**Comment by eightbox** [comment]
Hello,
I have same a problem, How to fix?

**Comment by frosty720** [comment]
The fork seems to fix the issues https://github.com/yenchihliao/tokenbridge-contracts

**Comment by yenchihliao** [comment]
Almost all the chains now enforces EIP155, which is not implemented in this repo. Therefore,  sending txs to those EIP155 chains would be reverted. My fork mentioned by @NicoDFS indeed fixed the issue
