### ISSUE TITLE
can't verified in bsc test and mumbai !

### ISSUE THREAD

**Issue by aoeng** [poanetwork/tokenbridge-contracts#680]
```
deploying foreignBridge storage

pending txHash 0xa26feb3ac4f311177e2bead0d8b1ee5d5c56cd70d285e9c331db8b0a08f88e90

tx status : 0xec2d839722da41705f48b984ce5a350233621a72 https://api-testnet.bscscan.com/api?mmm=etherscan
0xec2d839722da41705f48b984ce5a350233621a72 verified in etherscan
[Foreign] ForeignBridge Storage:  0xEC2D839722DA41705F48B984CE5A350233621A72

deploying foreignBridge implementation

pending txHash 0xb9fff9a713773b5e17c0a024bd36d142f7e3f9546775870f8e343a4490c2c439

tx status : 0xbb1facda76b20c614f541c7e70eff3b88e9ee020 https://api-testnet.bscscan.com/api?mmm=etherscan
```

in verified  foreignBridge implementation ,Too long without success, others soon!

**Comment by aoeng** [comment]
then
```
It was not possible to verify 0xbb1facda76b20c614f541c7e70eff3b88e9ee020 in etherscan
[Foreign] ForeignBridge Implementation:  0xBB1FacDa76b20C614F541C7e70eff3B88E9eE020

hooking up ForeignBridge storage to ForeignBridge implementation
pending txHash 0x9f05f81fd257de4b2fbe1d8e5dc9146f0b3d011435cb82374e756d740435b9ee

initializing Foreign Bridge with following parameters:

Foreign Validators: 0xCa02d199AdfE2971d9b151CE8ACE691057d424a8,
  ERC20_TOKEN_ADDRESS: 0x0Bc839c9B8c7ae31635f684840eA165be639dEc4,
  FOREIGN_DAILY_LIMIT: 300000000000000000000000 which is 300000 in eth,
  FOREIGN_MAX_AMOUNT_PER_TX: 150000000000000000000 which is 150 in eth,
  FOREIGN_MIN_AMOUNT_PER_TX: 500000000000000000 which is 0.5 in eth,
  FOREIGN_GAS_PRICE: 10000000000, FOREIGN_REQUIRED_BLOCK_CONFIRMATIONS : 1,
  HOME_DAILY_LIMIT: 300000000000000000000000 which is 300000 in eth,
  HOME_MAX_AMOUNT_PER_TX: 150000000000000000000 which is 150 in eth,
  FOREIGN_BRIDGE_OWNER: 0x3d6E8A7AE03B7935c5a42d4E1413291EfF269579,
  FOREIGN_TO_HOME_DECIMAL_SHIFT: 0,
  Home bridge Address: 0x1806611AbA220D5d38a2b35b8a1deB3078919Cd7
  
Error: web3 RPC failed: {"code":-32000,"message":"execution reverted"}
    at sendNodeRequest (/contracts/deploy/src/deploymentUtils.js:170:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
Error: TypeError: Cannot read property 'status' of undefined
    at initializeBridge (/contracts/deploy/src/erc_to_native/foreign.js:79:26)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
.env
```
#BRIDGE_MODE=ERC_TO_ERC
BRIDGE_MODE=ERC_TO_NATIVE

DEPLOYMENT_ACCOUNT_PRIVATE_KEY=11d415776e04118f14aef9d56dbe9509c0a54c282c40793de291bce96cabb088
DEPLOYMENT_GAS_LIMIT_EXTRA=0.2
HOME_DEPLOYMENT_GAS_PRICE=1000000000
FOREIGN_DEPLOYMENT_GAS_PRICE=5000000000
GET_RECEIPT_INTERVAL_IN_MILLISECONDS=3000

BRIDGEABLE_TOKEN_NAME=AAA
BRIDGEABLE_TOKEN_SYMBOL=AAA
BRIDGEABLE_TOKEN_DECIMALS=6

HOME_CHAIN_ID=2047
HOME_RPC_URL=https://rpc-test-a.pilotscan.org
HOME_BRIDGE_OWNER=0x0F025dc8A97C022031Ebb2cC255a2EEEB0968806
HOME_VALIDATORS_OWNER=0x16E5dC30E4cead60a37c9AE1658ba6661BB6B8b3
HOME_UPGRADEABLE_ADMIN=0x9CF8672F6b3E85463ADF0B0e45463169ca861AB2
HOME_DAILY_LIMIT=300000000000000000000000
HOME_MAX_AMOUNT_PER_TX=150000000000000000000
HOME_MIN_AMOUNT_PER_TX=500000000000000000
HOME_REQUIRED_BLOCK_CONFIRMATIONS=1
HOME_GAS_PRICE=1000000000

BLOCK_REWARD_ADDRESS=0x0000000000000000000000000000000000000000

# mumani
#FOREIGN_CHAIN_ID=80001
#FOREIGN_RPC_URL=https://polygon-mumbai.blockpi.network/v1/rpc/public

FOREIGN_CHAIN_ID=97
FOREIGN_RPC_URL=https://bsc-testnet.public.blastapi.io
FOREIGN_BRIDGE_OWNER=0x3d6E8A7AE03B7935c5a42d4E1413291EfF269579
FOREIGN_VALIDATORS_OWNER=0x6f72982eb4b98F761cd96741359d3212217b551c
FOREIGN_UPGRADEABLE_ADMIN=0x9aD96091aBa4DE67448b1938E26370eF335A6aF6
FOREIGN_DAILY_LIMIT=300000000000000000000000
FOREIGN_MAX_AMOUNT_PER_TX=150000000000000000000
FOREIGN_MIN_AMOUNT_PER_TX=500000000000000000
FOREIGN_REQUIRED_BLOCK_CONFIRMATIONS=1
FOREIGN_GAS_PRICE=10000000000

#for bridge erc_to_native mode
ERC20_TOKEN_ADDRESS=0x0Bc839c9B8c7ae31635f684840eA165be639dEc4

REQUIRED_NUMBER_OF_VALIDATORS=1
#If several validators are used, list them separated by space without quotes
#E.g. VALIDATORS=0x 0x 0x
VALIDATORS=0x6ab9A12b98b3f57249183Fdb07eA072e47aFaf1A
#Set to ONE_DIRECTION or BOTH_DIRECTIONS if fee will be charged on home side, set to false otherwise
HOME_REWARDABLE=false
# Valid only for rewards on erc_to_native mode. Supported values are BRIDGE_VALIDATORS_REWARD and POSDAO_REWARD
HOME_FEE_MANAGER_TYPE=BRIDGE_VALIDATORS_REWARD
#Set to ONE_DIRECTION or BOTH_DIRECTIONS if fee will be charged on foreign side, set to false otherwise
FOREIGN_REWARDABLE=false
#If HOME_REWARDABLE or FOREIGN_REWARDABLE set to true, list validators accounts were rewards should be transferred separated by space without quotes
#E.g. VALIDATORS_REWARD_ACCOUNTS=0x 0x 0x
VALIDATORS_REWARD_ACCOUNTS=0xe6E223b7EbD7e5E428C028a8EE97750AA14309ba

# Fee to be taken for every transaction directed from the Home network to the Foreign network
# E.g. 0.1% fee
HOME_TRANSACTIONS_FEE=0.001
# Fee to be taken for every transaction directed from the Foreign network to the Home network
FOREIGN_TRANSACTIONS_FEE=0.001

#If HOME_REWARDABLE is not false, list of accounts where rewards should be transferred separated by space without quotes
#E.g. HOME_MEDIATOR_REWARD_ACCOUNTS=0x 0x 0x
HOME_MEDIATOR_REWARD_ACCOUNTS=0xe6E223b7EbD7e5E428C028a8EE97750AA14309ba

#If FOREIGN_REWARDABLE is not false, list of accounts where rewards should be transferred separated by space without quotes
#E.g. FOREIGN_MEDIATOR_REWARD_ACCOUNTS=0x 0x 0x
FOREIGN_MEDIATOR_REWARD_ACCOUNTS=0x

#for bridge native_to_erc, erc_to_erc mode
DEPLOY_REWARDABLE_TOKEN=false
DPOS_STAKING_ADDRESS=

#如果外链和本地链之间的小数位数不同，则需要调整小数位数以调整桥接的代币数量。默认值为 0.
FOREIGN_TO_HOME_DECIMAL_SHIFT=

# For AMB mediators
HOME_AMB_BRIDGE=
FOREIGN_AMB_BRIDGE=

HOME_MEDIATOR_REQUEST_GAS_LIMIT=
FOREIGN_MEDIATOR_REQUEST_GAS_LIMIT=

# Supported explorers: Blockscout, etherscan
HOME_EXPLORER_URL=https://testnet.pilotscan.org/api
HOME_EXPLORER_API_KEY=

# Supported explorers: Blockscout, etherscan
#mumai
#FOREIGN_EXPLORER_URL=https://api-testnet.polygonscan.com/api?mmm=etherscan
#FOREIGN_EXPLORER_API_KEY=Z2N4VG89SJ9YT1866913W9ZY6QIUNSRR2F

FOREIGN_EXPLORER_URL=https://api-testnet.bscscan.com/api?mmm=etherscan
FOREIGN_EXPLORER_API_KEY=USEW58SXN8JZS8UR4ATRJY79CZH3SVPCRN
```

fix it?
